In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot
import seaborn as sns

In [42]:
df=pd.read_csv("weatherHistory.csv")

In [43]:
df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            96453 non-null  object
 1   Summary                   96453 non-null  object
 2   Precip Type               95936 non-null  object
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  float64
 8   Visibility (km)           96453 non-null  float64
 9   Loud Cover                96453 non-null  float64
 10  Pressure (millibars)      96453 non-null  float64
 11  Daily Summary             96453 non-null  object
dtypes: float64(8), object(4)
memory usage: 8.8+ MB

In [45]:
df.drop("Formatted Date", axis=1,inplace=True)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Summary                   96453 non-null  object
 1   Precip Type               95936 non-null  object
 2   Temperature (C)           96453 non-null  float64
 3   Apparent Temperature (C)  96453 non-null  float64
 4   Humidity                  96453 non-null  float64
 5   Wind Speed (km/h)         96453 non-null  float64
 6   Wind Bearing (degrees)    96453 non-null  float64
 7   Visibility (km)           96453 non-null  float64
 8   Loud Cover                96453 non-null  float64
 9   Pressure (millibars)      96453 non-null  float64
 10  Daily Summary             96453 non-null  object
dtypes: float64(8), object(3)
memory usage: 8.1+ MB

In [47]:
df["Summary"].unique()

array(['Partly Cloudy', 'Mostly Cloudy', 'Overcast', 'Foggy',
       'Breezy and Mostly Cloudy', 'Clear', 'Breezy and Partly Cloudy',
       'Breezy and Overcast', 'Humid and Mostly Cloudy',
       'Humid and Partly Cloudy', 'Windy and Foggy', 'Windy and Overcast',
       'Breezy and Foggy', 'Windy and Partly Cloudy', 'Breezy',
       'Dry and Partly Cloudy', 'Windy and Mostly Cloudy',
       'Dangerously Windy and Partly Cloudy', 'Dry', 'Windy',
       'Humid and Overcast', 'Light Rain', 'Drizzle', 'Windy and Dry',
       'Dry and Mostly Cloudy', 'Breezy and Dry', 'Rain'], dtype=object)

In [48]:
weather_order = [[
    "Clear",
    "Dry",
    "Partly Cloudy",
    "Breezy",
    "Breezy and Partly Cloudy",
    "Dry and Partly Cloudy",
    "Humid and Partly Cloudy",
    "Mostly Cloudy",
    "Breezy and Mostly Cloudy",
    "Dry and Mostly Cloudy",
    "Humid and Mostly Cloudy",
    "Overcast",
    "Humid and Overcast",
    "Breezy and Overcast",
    "Windy and Partly Cloudy",
    "Windy and Mostly Cloudy",
    "Windy and Overcast",
    "Breezy and Dry",
    "Windy and Dry",
    "Foggy",
    "Breezy and Foggy",
    "Windy and Foggy",
    "Drizzle",
    "Light Rain",
    "Rain",
    "Windy",
    "Dangerously Windy and Partly Cloudy"
]]

In [49]:
#Label and ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder

In [50]:
ord_encoder = OrdinalEncoder(categories=weather_order)

In [51]:
df["Summary"]=ord_encoder.fit_transform(df[["Summary"]])

In [52]:
df.head()

,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2.0,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2.0,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,7.0,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2.0,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,7.0,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [53]:
df["Precip Type"].unique()

array(['rain', 'snow', nan], dtype=object)

In [54]:
df["Precip Type"].mode()[0]

'rain'

In [55]:
df["Precip Type"]=df["Precip Type"].fillna(df["Precip Type"].mode()[0])

In [56]:
df["Precip Type"].unique()

array(['rain', 'snow'], dtype=object)

In [57]:
label_encode=LabelEncoder()
df["Precip Type"]=label_encode.fit_transform(df["Precip Type"])

In [58]:
df.head()

,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2.0,0,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2.0,0,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,7.0,0,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2.0,0,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,7.0,0,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [59]:
df["Precip Type"].unique()

array([0, 1])

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Summary                   96453 non-null  float64
 1   Precip Type               96453 non-null  int64
 2   Temperature (C)           96453 non-null  float64
 3   Apparent Temperature (C)  96453 non-null  float64
 4   Humidity                  96453 non-null  float64
 5   Wind Speed (km/h)         96453 non-null  float64
 6   Wind Bearing (degrees)    96453 non-null  float64
 7   Visibility (km)           96453 non-null  float64
 8   Loud Cover                96453 non-null  float64
 9   Pressure (millibars)      96453 non-null  float64
 10  Daily Summary             96453 non-null  object
dtypes: float64(9), int64(1), object(1)
memory usage: 8.1+ MB

In [61]:
df.drop("Daily Summary",axis=1,inplace=True)

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Summary                   96453 non-null  float64
 1   Precip Type               96453 non-null  int64
 2   Temperature (C)           96453 non-null  float64
 3   Apparent Temperature (C)  96453 non-null  float64
 4   Humidity                  96453 non-null  float64
 5   Wind Speed (km/h)         96453 non-null  float64
 6   Wind Bearing (degrees)    96453 non-null  float64
 7   Visibility (km)           96453 non-null  float64
 8   Loud Cover                96453 non-null  float64
 9   Pressure (millibars)      96453 non-null  float64
dtypes: float64(9), int64(1)
memory usage: 7.4 MB

In [63]:
#For linear regression

In [64]:
X=df.drop("Summary",axis=1)
y=df["Summary"]

In [65]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=15)

In [66]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [67]:
X_train

array([[-0.35297285,  0.08118378,  0.17320872, ...,  0.18644448,
         0.        ,  0.22343329],
       [-0.35297285, -0.329367  , -0.19339713, ..., -1.75696298,
         0.        ,  0.24120896],
       [-0.35297285, -0.44392579, -0.38760477, ...,  1.30793654,
         0.        ,  0.09959616],
       ...,
       [-0.35297285,  0.84471518,  0.85501251, ...,  0.20564811,
         0.        ,  0.1520767 ],
       [-0.35297285,  0.4376535 ,  0.49152229, ...,  0.22101102,
         0.        ,  0.08139727],
       [-0.35297285,  0.86216068,  0.87059067, ..., -0.08624708,
         0.        ,  0.06150546]])

In [68]:
from sklearn.linear_model import LinearRegression
linear_regression=LinearRegression()
linear_regression.fit(X_train,y_train)
y_pred_linear=linear_regression.predict(X_test)

In [69]:
from sklearn.metrics import r2_score
score_linear=r2_score(y_test,y_pred_linear)
print(score_linear)

0.3836916023939678

In [70]:
#FOR POLYNOMIAL REGRESSION
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=3,include_bias=True)
X_train_poly=poly.fit_transform(X_train)
X_test_poly=poly.transform(X_test)


poly_regression =LinearRegression()
poly_regression.fit(X_train_poly,y_train)
y_pred_poly=poly_regression.predict(X_test_poly)
score_poly=r2_score(y_test,y_pred_poly)
print(score_poly)

0.5441232573120534

In [71]:
#Lasso,LassoCV
from sklearn.linear_model import Lasso,LassoCV,Ridge,RidgeCV,ElasticNetCV,ElasticNet
lasso_regression=Lasso()
lasso_regression.fit(X_train,y_train)
y_pred_lasso=lasso_regression.predict(X_test)
score_lasso=r2_score(y_test,y_pred_lasso)
print("Lasso",score_lasso)

lassocv_regression=LassoCV(cv=5)
lassocv_regression.fit(X_train,y_train)
y_pred_lassocv=lassocv_regression.predict(X_test)
score_lassocv=r2_score(y_test,y_pred_lassocv)
print("Lassocv",score_lassocv)

Lasso 0.2947670103193465
Lassocv 0.38368559371425637

In [72]:
#Ridge,RidgeCV
ridge_regression=Ridge()
ridge_regression.fit(X_train,y_train)
y_pred_ridge=ridge_regression.predict(X_test)
score_ridge=r2_score(y_test,y_pred_ridge)
print("Ridge",score_ridge)


ridge_regressioncv=RidgeCV(cv=5)
ridge_regressioncv.fit(X_train,y_train)
y_pred_ridgecv=ridge_regressioncv.predict(X_test)
score_ridgecv=r2_score(y_test,y_pred_ridgecv)
print("Ridgecv",score_ridgecv)

Ridge 0.38369280269806716
Ridgecv 0.38369172401624585

In [73]:
#ElasticNet vs ElasticElasticNetCV
elastic_regression=ElasticNet()
elastic_regression.fit(X_train,y_train)
y_pred_elastic=elastic_regression.predict(X_test)
score_elastic=r2_score(y_test,y_pred_elastic)
print("Elastic",score_elastic)

elastic_regressioncv=ElasticNetCV(cv=5)
elastic_regressioncv.fit(X_train,y_train)
y_pred_elasticcv=elastic_regressioncv.predict(X_test)
score_elasticcv=r2_score(y_test,y_pred_elasticcv)
print("Elastic",score_elasticcv)

Elastic 0.3009663436500386
Elastic 0.38344354902747135

In [74]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import  accuracy_score,classification_report,confusion_matrix
logistic_regression = LogisticRegression()
logistic_regression.fit(X_train,y_train)
y_pred_logistic=logistic_regression.predict(X_test)
accuracy_socre=accuracy_score(y_test,y_pred_logistic)
print(accuracy_socre)
print("---------------------------------")
classi_score=classification_report(y_test,y_pred_logistic)
print(classi_score)
print("---------------------------------")
confux_score=confusion_matrix(y_test,y_pred_logistic)
print(confux_score)

0.4964749792645839
---------------------------------
              precision    recall  f1-score   support

         0.0       0.56      0.06      0.11      3233
         1.0       0.00      0.00      0.00         9
         2.0       0.50      0.66      0.57      9548
         3.0       0.50      0.35      0.41        20
         4.0       0.44      0.26      0.32       117
         5.0       0.00      0.00      0.00        23
         6.0       0.00      0.00      0.00         4
         7.0       0.40      0.39      0.39      8374
         8.0       0.35      0.34      0.34       152
         9.0       0.00      0.00      0.00         1
        10.0       0.00      0.00      0.00        12
        11.0       0.47      0.46      0.46      5030
        12.0       0.00      0.00      0.00         3
        13.0       0.50      0.64      0.56       150
        14.0       0.00      0.00      0.00        24
        15.0       0.00      0.00      0.00        13
        16.0       0.00      0.00      0.00        16
        17.0       0.00      0.00      0.00         1
        19.0       0.89      0.97      0.93      2154
        20.0       0.80      0.36      0.50        11
        21.0       0.00      0.00      0.00         1
        22.0       0.00      0.00      0.00        13
        23.0       0.00      0.00      0.00        21
        24.0       0.00      0.00      0.00         5
        25.0       0.00      0.00      0.00         1

    accuracy                           0.50     28936
   macro avg       0.22      0.18      0.18     28936
weighted avg       0.50      0.50      0.47     28936

---------------------------------
[[ 207    0 1846    1    0    0    0  668    0    0    0  430    0    0
     0    0    0    0   81    0    0    0    0    0    0]
 [   0    0    9    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]
 [  65    0 6314    0    0    0    0 2382    2    0    0  753    0    1
     0    0    0    0   31    0    0    0    0    0    0]
 [   0    0    1    7    1    0    0    3    0    0    0    2    0    5
     0    0    0    0    1    0    0    0    0    0    0]
 [   0    0    4    1   30    0    0   16   48    0    0    4    0   14
     0    0    0    0    0    0    0    0    0    0    0]
 [   0    0   23    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    2    0    0    0    0    2    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]
 [  47    0 3701    1    0    0    0 3257    5    0    0 1320    0    2
     0    0    0    0   41    0    0    0    0    0    0]
 [   0    0    1    2   20    0    0   20   51    0    0    8    0   50
     0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    1    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    5    0    0    0    0    5    0    0    0    2    0    0
     0    0    0    0    0    0    0    0    0    0    0]
 [  41    0  783    1    0    0    0 1814    1    0    0 2301    0    3
     0    0    0    0   86    0    0    0    0    0    0]
 [   0    0    1    0    0    0    0    2    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    5    0    0   12   17    0    0   19    0   96
     0    0    0    0    0    1    0    0    0    0    0]
 [   0    0    0    0    5    0    0    0   15    0    0    0    0    4
     0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    2    0    0    0    7    0    0    0    0    4
     0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    4    0    0    0    1    0    0    0    0   11
     0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    1    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]
 [  10    0    3    0    0    0    0    5    0    0    0   37    0    0
     0    0    0    0 2099    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    7    4    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    1
     0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    8    0    0    0    0    0    0
     0    0    0    0    5    0    0    0    0    0    0]
 [   0    0    1    0    0    0    0    2    0    0    0   17    0    0
     0    0    0    0    1    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    1    0    0
     0    0    0    0    4    0    0    0    0    0    0]
 [   0    0    0    1    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]]

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [75]:
#hyperparameter
logistic_regression=LogisticRegression()

In [77]:
penalty=["l1","l2","elasticnet"]
c_value=[100,10,1,0.1,0.01]
solver = ["newton-cg","lbfgs","liblinear","newton-cholesky","sag","saga"]
class_weight=[{0:w,1:y} for w in [1,10,50,100] for y in [1,10,50,100]]

In [78]:
prams=dict(penalty=penalty,C=c_value,solver=solver,class_weight=class_weight)

In [79]:
#grid search cv
from sklearn.model_selection import GridSearchCV,StratifiedKFold

In [80]:
cv=StratifiedKFold()
grid_regression=GridSearchCV(estimator=logistic_regression,param_grid=prams,cv=cv,scoring="accuracy",n_jobs=-1)

In [ ]:
import warnings
warnings.filterwarnings("ignore")
grid_regression.fit(X_train,y_train)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

In [ ]:
grid_regression.best_score_

In [ ]:
y_pred_grid=grid_regression.predict(X_test)
accuracy_socre=accuracy_score(y_test,y_pred_grid)
print(accuracy_socre)
print("---------------------------------")
classi_score=classification_report(y_test,y_pred_grid)
print(classi_score)
print("---------------------------------")
confux_score=confusion_matrix(y_test,y_pred_grid)
print(confux_score)

In [ ]:
#Multiclass 
from sklearn.multiclass import OneVsOneClassifier,OneVsRestClassifier

In [ ]:
onevsone=OneVsOneClassifier(estimator=LogisticRegression())
onevsrest=OneVsRestClassifier(estimator=LogisticRegression())

In [ ]:
onevsone.fit(X_train,y_train)
y_pred_onevsone=onevsone.predict(X_test)
score=accuracy_score(y_test,y_pred_onevsone)
print("Score",score)

In [ ]:
onevsrest.fit(X_train,y_train)
y_pred_onevsrest=onevsrest.predict(X_test)
score=accuracy_score(y_test,y_pred_onevsrest)
print("Score",score)