In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [51]:
df=pd.read_csv("insurance.csv")

In [52]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [54]:
X=df.drop("charges",axis=1)
y=df["charges"]

In [55]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=15)

In [56]:
from sklearn.preprocessing import LabelEncoder,StandardScaler
encode=LabelEncoder()
X_train["sex"]=encode.fit_transform(X_train["sex"])
X_test["sex"]=encode.transform(X_test["sex"])
X_train["smoker"]=encode.fit_transform(X_train["smoker"])
X_test["smoker"]=encode.transform(X_test["smoker"])
X_train["region"]=encode.fit_transform(X_train["region"])
X_test["region"]=encode.transform(X_test["region"])

In [57]:
X_train

      age  sex     bmi  children  smoker  region
525    18    0  33.880         0       0       2
183    44    0  26.410         0       0       1
821    26    1  17.670         0       0       1
1237   58    0  28.215         0       0       1
1185   45    1  23.560         2       0       0
...   ...  ...     ...       ...     ...     ...
1223   20    0  24.420         0       1       2
667    40    0  32.775         2       1       1
156    48    1  24.420         0       1       2
384    44    1  22.135         2       0       0
645    48    1  30.780         3       0       0

[936 rows x 6 columns]

In [58]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [60]:
X_train

array([[-1.53133353, -1.01074145,  0.51945743, -0.8968325 , -0.49632471,
         0.43482455],
       [ 0.31254024, -1.01074145, -0.7011404 , -0.8968325 , -0.49632471,
        -0.45967167],
       [-0.96398775,  0.98937271, -2.1292562 , -0.8968325 , -0.49632471,
        -0.45967167],
       ...,
       [ 0.59621313,  0.98937271, -1.02630635, -0.8968325 ,  2.01481003,
         0.43482455],
       [ 0.31254024,  0.98937271, -1.3996753 ,  0.75559903, -0.49632471,
        -1.35416788],
       [ 0.59621313,  0.98937271,  0.0129175 ,  1.5818148 , -0.49632471,
        -1.35416788]])

In [61]:
from sklearn.linear_model import LinearRegression
linear=LinearRegression()
linear.fit(X_train,y_train)
y_pred_lin=linear.predict(X_test)

In [62]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
print("mse:",mean_squared_error(y_test,y_pred_lin))
print("mae:",mean_absolute_error(y_test,y_pred_lin))
print("score:",r2_score(y_test,y_pred_lin))

mse: 33549586.78867716
mae: 4154.199454421524
score: 0.7866962933963438

In [63]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=2)
X_train_poly=poly.fit_transform(X_train)
X_test_poly=poly.transform(X_test)

In [64]:
poly_regression=LinearRegression()
poly_regression.fit(X_train_poly,y_train)
y_pred_poly=poly_regression.predict(X_test_poly)
print("mse:",mean_squared_error(y_test,y_pred_poly))
print("mae:",mean_absolute_error(y_test,y_pred_poly))
print("score:",r2_score(y_test,y_pred_poly))

mse: 20858049.457634646
mae: 2863.958701434549
score: 0.8673873603910555

In [65]:
#Ridge Lasso Elastic
from sklearn.linear_model import RidgeCV,LassoCV,ElasticNetCV
ridgecv=RidgeCV(cv=5)
ridgecv.fit(X_train,y_train)
y_pred_ridge=ridgecv.predict(X_test)
print("mse:",mean_squared_error(y_test,y_pred_ridge))
print("mae:",mean_absolute_error(y_test,y_pred_ridge))
print("score:",r2_score(y_test,y_pred_ridge))

mse: 33579253.233723596
mae: 4171.40696831627
score: 0.7865076781764302

In [66]:
lassocv=LassoCV(cv=5)
lassocv.fit(X_train,y_train)
y_pred_lasso=lassocv.predict(X_test)
print("mse:",mean_squared_error(y_test,y_pred_lasso))
print("mae:",mean_absolute_error(y_test,y_pred_lasso))
print("score:",r2_score(y_test,y_pred_lasso))

mse: 33540450.5424277
mae: 4150.835992914014
score: 0.7867543804065276

In [67]:
elasticcv=ElasticNetCV(cv=5)
elasticcv.fit(X_train,y_train)
y_pred_elastic=elasticcv.predict(X_test)
print("mse:",mean_squared_error(y_test,y_pred_elastic))
print("mae:",mean_absolute_error(y_test,y_pred_elastic))
print("score:",r2_score(y_test,y_pred_elastic))

mse: 135002175.96667284
mae: 8852.157647180189
score: 0.14167453940240393

In [68]:
#SVR
from sklearn.svm import SVR
svr=SVR()
svr.fit(X_train,y_train)

SVR()

In [69]:
y_pred_svr=svr.predict(X_test)
print("mse:",mean_squared_error(y_test,y_pred_svr))
print("mae:",mean_absolute_error(y_test,y_pred_svr))
print("score:",r2_score(y_test,y_pred_svr))

mse: 169700182.7100049
mae: 8701.32572500056
score: -0.07893066496956935

In [70]:
X_train

array([[-1.53133353, -1.01074145,  0.51945743, -0.8968325 , -0.49632471,
         0.43482455],
       [ 0.31254024, -1.01074145, -0.7011404 , -0.8968325 , -0.49632471,
        -0.45967167],
       [-0.96398775,  0.98937271, -2.1292562 , -0.8968325 , -0.49632471,
        -0.45967167],
       ...,
       [ 0.59621313,  0.98937271, -1.02630635, -0.8968325 ,  2.01481003,
         0.43482455],
       [ 0.31254024,  0.98937271, -1.3996753 ,  0.75559903, -0.49632471,
        -1.35416788],
       [ 0.59621313,  0.98937271,  0.0129175 ,  1.5818148 , -0.49632471,
        -1.35416788]])

In [71]:
param_grid={"C":[0.1,1,10,100,1000],
            "gamma":[1,0.1,0.01,0.001],
            "kernel":["linear", "poly", "rbf", "sigmoid"]}

In [73]:
from sklearn.model_selection import GridSearchCV,StratifiedKFold
cv=5
grid_svr=GridSearchCV(estimator=svr,param_grid=param_grid,cv=cv,n_jobs=-1)
grid_svr.fit(X_train,y_train)
y_pred_svr=grid_svr.predict(X_test)
print("mse:",mean_squared_error(y_test,y_pred_svr))
print("mae:",mean_absolute_error(y_test,y_pred_svr))
print("score:",r2_score(y_test,y_pred_svr))

Exception ignored in: <function ResourceTracker.__del__ at 0x1061c1bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x107269bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x1079e9bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x1118d5bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x106815bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x1107d5bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x10a715bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x106fedbc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x108ed5bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x103921bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x1056edbc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

mse: 21899019.833594058
mae: 2272.989379491549
score: 0.8607690124198762